version: '3'
services:
  portfolio_php_app:
    build: ./docker
    container_name: 'portfolio_php_app'
    volumes:
      - .:/var/www/html
    ports:
      - '8080:80'
    networks:
      - portfolio_network
      - proxy_network
networks:
  portfolio_network:
  proxy_network:
    external: true
