version: '3'
services:
  portfolio_php_app:
    build: ./docker
    container_name: 'portfolio_php_app'
    volumes:
      - .:/var/www/html
      - ./docker/apache/vhost.conf:/etc/apache2/conf-enabled/vhost.conf
    ports:
      - '8080:80'
    networks:
      - portfolio_network
      - proxy_network
networks:
  portfolio_network:
  proxy_network:
    external: true
